from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class ActivityShikigamiAssets: 


	# Click Rule Assets
	# description 
	C_RANDOM_LEFT = RuleClick(roi_front=(21,23,290,599), roi_back=(21,23,290,599), name="random_left")
	# description 
	C_RANDOM_RIGHT = RuleClick(roi_front=(969,55,296,638), roi_back=(969,55,296,638), name="random_right")
	# description 
	C_RANDOM_TOP = RuleClick(roi_front=(85,46,1159,101), roi_back=(85,46,1159,101), name="random_top")
	# description 
	C_RANDOM_BOTTOM = RuleClick(roi_front=(182,539,1063,100), roi_back=(182,539,1063,100), name="random_bottom")
	# description 
	C_RANDOM_ALL = RuleClick(roi_front=(42,94,1207,543), roi_back=(42,94,1207,543), name="random_all")


	# Image Rule Assets
	# 进入活动 
	I_SHI = RuleImage(roi_front=(431,152,60,59), roi_back=(431,152,60,59), threshold=0.7, method="Template matching", file="./tasks/ActivityShikigami/as/as_new_shi.png")

	I_GE_LOU = RuleImage(roi_front=(567,205,37,33), roi_back=(567,205,37,33), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/as_new_gelopu.png")

	I_GOLD = RuleImage(roi_front=(127,438,92,54), roi_back=(127,438,92,54), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/as_new_gold.png")

	# 左上角返回 
	I_BACK_GREEN = RuleImage(roi_front=(23,27,44,44), roi_back=(23,27,44,44), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/as_back_green.png")
	# 进入爬塔 
	I_BATTLE = RuleImage(roi_front=(642,173,47,172), roi_back=(618,151,105,220), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/as_battle.png")
	# 归鹿之途 
	I_DRUM = RuleImage(roi_front=(1011,114,29,31), roi_back=(1011,114,29,31), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/as_drum.png")
	# 上锁图标 
	I_LOCK = RuleImage(roi_front=(801,649,25,32), roi_back=(801,649,25,32), threshold=0.7, method="Template matching", file="./tasks/ActivityShikigami/as/as_lock.png")
	# 还未上锁图片 
	I_UNLOCK = RuleImage(roi_front=(800,650,28,24), roi_back=(800,650,28,24), threshold=0.7, method="Template matching", file="./tasks/ActivityShikigami/as/as_unlock.png")
	# 点击战斗 
	I_FIRE = RuleImage(roi_front=(1139,581,83,66), roi_back=(1139,581,83,66), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/as_new_fire.png")
	# 体力按钮 
	I_AP = RuleImage(roi_front=(1127,494,80,33), roi_back=(1127,494,80,33), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/as_ap.png")
	# 活动体力 
	I_AP_ACTIVITY = RuleImage(roi_front=(1135,497,62,27), roi_back=(1135,497,62,27), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/as_ap_activity.png")
	# 切换按键 
	I_SWITCH = RuleImage(roi_front=(1217,494,33,30), roi_back=(1217,494,33,30), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/as_switch.png")
	# 购买活动的体力 
	I_BUY_JADE = RuleImage(roi_front=(1004,192,38,42), roi_back=(836,619,38,42), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/as_buy_jade.png")
	# 增加到最大 
	I_ADD_MAX = RuleImage(roi_front=(17,24,33,37), roi_back=(974,524,57,54), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/as_add_max.png")
	# description 
	I_NEW = RuleImage(roi_front=(1004,192,65,52), roi_back=(0,0,100,100), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/as_new.png")


	# Ocr Rule Assets
	# 体力的数量检测 
	O_REMAIN_AP = RuleOcr(roi=(1159,674,104,34), area=(1159,674,104,34), mode="DigitCounter", method="Default", keyword="", name="remain_ap")
	# 活动体力的剩余检测 
	O_REMAIN_AP_ACTIVITY = RuleOcr(roi=(910,22,100,35), area=(910,22,100,35), mode="DigitCounter", method="Default", keyword="", name="remain_ap_activity")
	# 还有多少次购买体力的机会 
	O_REMAIN_BUY = RuleOcr(roi=(1010,22,39,42), area=(1010,22,39,42), mode="DigitCounter", method="Default", keyword="", name="remain_buy")

	O_NEED_AP_GAME = RuleOcr(roi=(1138,497,75,29), area=(1138,497,75,29), mode="Digit", method="Default", keyword="", name="need_ap_game")

	O_NEED_AP_AC = RuleOcr(roi=(1156,494,43,32), area=(1156,494,43,32), mode="Digit", method="Default", keyword="", name="need_ap_ac")


